In [6]:
#1.
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)
print(array_list.dtype)
print(type(list_))
# The datatype of both are different.

<U1
<class 'list'>


In [15]:
#2.
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

for i in list_:
    print(i,type(i),sep=" ")
for i in array_list:
    print(i,i.dtype,sep=" ")

1 <class 'str'>
2 <class 'str'>
3 <class 'str'>
4 <class 'str'>
5 <class 'str'>
1 <U1
2 <U1
3 <U1
4 <U1
5 <U1


In [13]:
#3.
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)
array_list = np.array(object = list_, dtype = int)
for i in list_:
    print(i,type(i),sep=" ")
for i in array_list:
    print(i,i.dtype,sep=" ")

1 <class 'str'>
2 <class 'str'>
3 <class 'str'>
4 <class 'str'>
5 <class 'str'>
1 int64
2 int64
3 int64
4 int64
5 int64


In [18]:
#4.

import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
print(num_array.shape)
print(num_array.size)

(2, 3)
6


In [19]:
#5.

import numpy as np
array_list=np.zeros((3,3))
print(array_list)
print(array_list.shape)
print(array_list.size)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)
9


In [21]:
#6.

import numpy as np
array_list=np.eye(5,5)
print(array_list)
print(array_list.shape)
print(array_list.size)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
(5, 5)
25
